var userClips = [
  {
    "filepath": "../_video/Reel \u22c5 Evisarize - Parasites.mp4",
    "filename": "Reel \u22c5 Evisarize - Parasites.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "vertical_full",
    "start": 47.0,
    "end": 107.0,
    "artist": "Evisarize",
    "title": "Parasites",
    "timestamp": "2026-07-25 05:51:30"
  },
  {
    "filepath": "../_audio/Evisarize - Parasites (0.47 - 1.47).mp3",
    "filename": "Evisarize - Parasites (0.47 - 1.47).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 47.0,
    "end": 107.0,
    "artist": "Evisarize",
    "title": "Parasites",
    "timestamp": "2026-07-25 05:51:30"
  },
  {
    "filepath": "../_video/Reel Artist \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "filename": "Reel Artist \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "kind": "video",
    "template": "reel_artist",
    "platform": "default",
    "start": 0.0,
    "end": 121.987188,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-25 01:22:21"
  },
  {
    "filepath": "../_audio/Ritual Fog - Funeral Fumes (0.00 - 2.01.99).mp3",
    "filename": "Ritual Fog - Funeral Fumes (0.00 - 2.01.99).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0.0,
    "end": 121.987188,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-25 01:22:21"
  },
  {
    "filepath": "../_video/Reel Artist \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "filename": "Reel Artist \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "kind": "video",
    "template": "reel_artist",
    "platform": "default",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-25 01:10:26"
  },
  {
    "filepath": "../_audio/Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "filename": "Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-25 01:10:26"
  },
  {
    "filepath": "../_video/Reel Artist \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "filename": "Reel Artist \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "kind": "video",
    "template": "reel_artist",
    "platform": "instagram",
    "start": 0.0,
    "end": 60.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:42:40"
  },
  {
    "filepath": "../_audio/Ritual Fog - Funeral Fumes (0.00 - 1.00).mp3",
    "filename": "Ritual Fog - Funeral Fumes (0.00 - 1.00).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0.0,
    "end": 60.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:42:40"
  },
  {
    "filepath": "../_video/Reel \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "filename": "Reel \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "instagram",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:31:23"
  },
  {
    "filepath": "../_audio/Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "filename": "Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:31:23"
  },
  {
    "filepath": "../_video/Reel \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "filename": "Reel \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "instagram",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:29:16"
  },
  {
    "filepath": "../_audio/Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "filename": "Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:29:16"
  },
  {
    "filepath": "../_video/Reel \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "filename": "Reel \u22c5 Ritual Fog - Funeral Fumes.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "instagram",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:22:35"
  },
  {
    "filepath": "../_audio/Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "filename": "Ritual Fog - Funeral Fumes (0.20 - 1.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 20.0,
    "end": 80.0,
    "artist": "Ritual Fog",
    "title": "Funeral Fumes",
    "timestamp": "2026-07-24 22:22:34"
  },
  {
    "filepath": "../_video/Spinner Story \u22c5 Survival Method - Total Extinction.mp4",
    "filename": "Spinner Story \u22c5 Survival Method - Total Extinction.mp4",
    "kind": "video",
    "template": "spinner_story",
    "platform": "instagram",
    "start": 65.0,
    "end": 125.0,
    "artist": "Survival Method",
    "title": "Total Extinction",
    "timestamp": "2026-07-24 21:59:22"
  },
  {
    "filepath": "../_audio/Survival Method - Total Extinction (1.05 - 2.05).mp3",
    "filename": "Survival Method - Total Extinction (1.05 - 2.05).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 65.0,
    "end": 125.0,
    "artist": "Survival Method",
    "title": "Total Extinction",
    "timestamp": "2026-07-24 21:59:21"
  },
  {
    "filepath": "../_video/Reel \u22c5 Survival Method - Total Extinction.mp4",
    "filename": "Reel \u22c5 Survival Method - Total Extinction.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "instagram",
    "start": 65.0,
    "end": 125.0,
    "artist": "Survival Method",
    "title": "Total Extinction",
    "timestamp": "2026-07-24 15:43:18"
  },
  {
    "filepath": "../_audio/Survival Method - Total Extinction (1.05 - 2.05).mp3",
    "filename": "Survival Method - Total Extinction (1.05 - 2.05).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 65.0,
    "end": 125.0,
    "artist": "Survival Method",
    "title": "Total Extinction",
    "timestamp": "2026-07-24 15:43:17"
  },
  {
    "filepath": "../_video/Reel \u22c5 Survival Method - Total Extinction.mp4",
    "filename": "Reel \u22c5 Survival Method - Total Extinction.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "vertical_full",
    "start": 65.0,
    "end": 125.0,
    "artist": "Survival Method",
    "title": "Total Extinction",
    "timestamp": "2026-07-24 15:28:04"
  },
  {
    "filepath": "../_audio/Survival Method - Total Extinction (1.05 - 2.05).mp3",
    "filename": "Survival Method - Total Extinction (1.05 - 2.05).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 65.0,
    "end": 125.0,
    "artist": "Survival Method",
    "title": "Total Extinction",
    "timestamp": "2026-07-24 15:28:04"
  },
  {
    "filepath": "../_video/Reel \u22c5 Warbringer - Crushed Beneath the Tracks.mp4",
    "filename": "Reel \u22c5 Warbringer - Crushed Beneath the Tracks.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "vertical_full",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Crushed Beneath the Tracks",
    "timestamp": "2026-07-24 15:01:39"
  },
  {
    "filepath": "../_audio/Warbringer - Crushed Beneath the Tracks (0.00 - 1.00).mp3",
    "filename": "Warbringer - Crushed Beneath the Tracks (0.00 - 1.00).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Crushed Beneath the Tracks",
    "timestamp": "2026-07-24 15:01:37"
  },
  {
    "filepath": "../_video/Reel \u22c5 Warbringer - Silhouettes.mp4",
    "filename": "Reel \u22c5 Warbringer - Silhouettes.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "vertical_full",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Silhouettes",
    "timestamp": "2026-07-24 14:57:27"
  },
  {
    "filepath": "../_audio/Warbringer - Silhouettes (0.00 - 1.00).mp3",
    "filename": "Warbringer - Silhouettes (0.00 - 1.00).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Silhouettes",
    "timestamp": "2026-07-24 14:57:26"
  },
  {
    "filepath": "../_video/Reel \u22c5 Warbringer - Total War.mp4",
    "filename": "Reel \u22c5 Warbringer - Total War.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "vertical_full",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Total War",
    "timestamp": "2026-07-24 08:01:47"
  },
  {
    "filepath": "../_audio/Warbringer - Total War (0.00 - 1.00).mp3",
    "filename": "Warbringer - Total War (0.00 - 1.00).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Total War",
    "timestamp": "2026-07-24 08:01:47"
  },
  {
    "filepath": "../_video/Reel \u22c5 Warbringer - Hell on Earth.mp4",
    "filename": "Reel \u22c5 Warbringer - Hell on Earth.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "vertical_full",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Hell on Earth",
    "timestamp": "2026-07-24 07:38:44"
  },
  {
    "filepath": "../_audio/Warbringer - Hell on Earth (0.00 - 1.00).mp3",
    "filename": "Warbringer - Hell on Earth (0.00 - 1.00).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0.0,
    "end": 60.0,
    "artist": "Warbringer",
    "title": "Hell on Earth",
    "timestamp": "2026-07-24 07:38:43"
  },
  {
    "filepath": "../_video/Reel \u22c5 Sadistic Ritual - Dire Avidity.mp4",
    "filename": "Reel \u22c5 Sadistic Ritual - Dire Avidity.mp4",
    "kind": "video",
    "template": "reel",
    "platform": "vertical_full",
    "start": 0.0,
    "end": 60.0,
    "artist": "Sadistic Ritual",
    "title": "Dire Avidity",
    "timestamp": "2026-07-09 22:52:59"
  },
  {
    "filepath": "../_audio/Sadistic Ritual - Dire Avidity (0.00 - 1.00).mp3",
    "filename": "Sadistic Ritual - Dire Avidity (0.00 - 1.00).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0.0,
    "end": 60.0,
    "artist": "Sadistic Ritual",
    "title": "Dire Avidity",
    "timestamp": "2026-07-09 22:52:59"
  },
  {
    "filepath": "../_video/Vinyl Sleeve Pro \u22c5 Deicide - They Are the Children of the Underworld.mp4",
    "filename": "Vinyl Sleeve Pro \u22c5 Deicide - They Are the Children of the Underworld.mp4",
    "kind": "video",
    "template": "vinyl_sleeve_pro",
    "platform": "default",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-06-01 03:40:32"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-06-01 03:40:28"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Vinyl Sleeve.mp4",
    "filename": "Vinyl Sleeve.mp4",
    "kind": "video",
    "template": "vinyl_sleeve",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 20:51:25"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.20).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 20:51:24"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Waveform Stage.mp4",
    "filename": "Waveform Stage.mp4",
    "kind": "video",
    "template": "waveform_stage",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 20:51:20"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 20:51:20"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Spinner.mp4",
    "filename": "Spinner.mp4",
    "kind": "video",
    "template": "spinner",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 20:51:03"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 20:51:03"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Cinematic.mp4",
    "filename": "Cinematic.mp4",
    "kind": "video",
    "template": "cinematic",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 20:50:48"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 20:50:47"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Glass Card.mp4",
    "filename": "Glass Card.mp4",
    "kind": "video",
    "template": "glass_card",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 20:50:10"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.15).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 20:50:10"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Neon Pulse.mp4",
    "filename": "Neon Pulse.mp4",
    "kind": "video",
    "template": "neon_pulse",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 20:49:31"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.15).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 20:49:31"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Artist Focus.mp4",
    "filename": "Artist Focus.mp4",
    "kind": "video",
    "template": "artist_focus",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 20:49:24"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.20).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 20:49:24"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Metadata Card.mp4",
    "filename": "Metadata Card.mp4",
    "kind": "video",
    "template": "metadata_card",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 20:49:22"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Poster.mp4",
    "filename": "Poster.mp4",
    "kind": "video",
    "template": "poster",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 20:49:22"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 20:49:22"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 20:49:22"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Fade Premium.mp4",
    "filename": "Fade Premium.mp4",
    "kind": "video",
    "template": "fade_premium",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 20:49:16"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 20:49:16"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Spinner.mp4",
    "filename": "Spinner.mp4",
    "kind": "video",
    "template": "spinner",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:33:40"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:33:39"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Vinyl_Sleeve.mp4",
    "filename": "Vinyl_Sleeve.mp4",
    "kind": "video",
    "template": "vinyl_sleeve",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:32:43"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.20).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:32:43"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Metadata_Card.mp4",
    "filename": "Metadata_Card.mp4",
    "kind": "video",
    "template": "metadata_card",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:32:10"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:32:09"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Glass_Card.mp4",
    "filename": "Glass_Card.mp4",
    "kind": "video",
    "template": "glass_card",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:32:00"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.15).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:32:00"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Waveform_Stage.mp4",
    "filename": "Waveform_Stage.mp4",
    "kind": "video",
    "template": "waveform_stage",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:30:03"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:30:01"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Waveform_Pulse.mp4",
    "filename": "Waveform_Pulse.mp4",
    "kind": "video",
    "template": "waveform_pulse",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:29:11"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:29:09"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Vertical.mp4",
    "filename": "Vertical.mp4",
    "kind": "video",
    "template": "vertical",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:28:34"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.20).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:28:34"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Poster.mp4",
    "filename": "Poster.mp4",
    "kind": "video",
    "template": "poster",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:27:36"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:27:35"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Fade_Premium.mp4",
    "filename": "Fade_Premium.mp4",
    "kind": "video",
    "template": "fade_premium",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:27:15"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.15).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 15.0,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:27:14"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Cinematic.mp4",
    "filename": "Cinematic.mp4",
    "kind": "video",
    "template": "cinematic",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:26:58"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:26:57"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Artist_Focus.mp4",
    "filename": "Artist_Focus.mp4",
    "kind": "video",
    "template": "artist_focus",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:26:44"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.20).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:26:43"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Vertical \u22c5 R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (1.14 - 1.59) [smoke_test].mp4",
    "filename": "Vertical \u22c5 R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (1.14 - 1.59) [smoke_test].mp4",
    "kind": "video",
    "template": "vertical",
    "platform": "vertical_full",
    "start": 0,
    "end": 45.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:08:49"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.45).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.45).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 45.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:08:49"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Vinyl Sleeve \u22c5 Skeletal Remains - Tombs of Chaos (4.12 - 4.32) [smoke_test].mp4",
    "filename": "Vinyl Sleeve \u22c5 Skeletal Remains - Tombs of Chaos (4.12 - 4.32) [smoke_test].mp4",
    "kind": "video",
    "template": "vinyl_sleeve",
    "platform": "vertical_full",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:08:12"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:08:12"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Waveform Pulse \u22c5 Deicide - They Are the Children of the Underworld (0.50 - 1.20) [smoke_test].mp4",
    "filename": "Waveform Pulse \u22c5 Deicide - They Are the Children of the Underworld (0.50 - 1.20) [smoke_test].mp4",
    "kind": "video",
    "template": "waveform_pulse",
    "platform": "vertical_full",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:08:00"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:08:00"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Waveform Stage \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "filename": "Waveform Stage \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "kind": "video",
    "template": "waveform_stage",
    "platform": "vertical_full",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:07:50"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:07:50"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Spinner \u22c5 Deicide - They Are the Children of the Underworld (0.50 - 1.20) [smoke_test].mp4",
    "filename": "Spinner \u22c5 Deicide - They Are the Children of the Underworld (0.50 - 1.20) [smoke_test].mp4",
    "kind": "video",
    "template": "spinner",
    "platform": "default",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:06:25"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:06:25"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Metadata Card \u22c5 R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (1.14 - 1.59) [smoke_test].mp4",
    "filename": "Metadata Card \u22c5 R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (1.14 - 1.59) [smoke_test].mp4",
    "kind": "video",
    "template": "metadata_card",
    "platform": "vertical_full",
    "start": 0,
    "end": 45.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:06:11"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.45).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.45).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 45.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:06:10"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Neon Pulse \u22c5 Skeletal Remains - Tombs of Chaos (4.12 - 4.32) [smoke_test].mp4",
    "filename": "Neon Pulse \u22c5 Skeletal Remains - Tombs of Chaos (4.12 - 4.32) [smoke_test].mp4",
    "kind": "video",
    "template": "neon_pulse",
    "platform": "vertical_full",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:06:05"
  },
  {
    "filepath": "../_audio/Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "filename": "Skeletal Remains - Tombs of Chaos (0.00 - 0.20).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 20.0,
    "artist": "Skeletal Remains",
    "title": "Tombs of Chaos",
    "timestamp": "2026-05-31 18:06:05"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Concert Poster \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "filename": "Concert Poster \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "kind": "video",
    "template": "poster",
    "platform": "vertical_full",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:05:56"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:05:55"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Fade Premium \u22c5 R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (1.14 - 1.59) [smoke_test].mp4",
    "filename": "Fade Premium \u22c5 R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (1.14 - 1.59) [smoke_test].mp4",
    "kind": "video",
    "template": "fade_premium",
    "platform": "default",
    "start": 0,
    "end": 45.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:05:25"
  },
  {
    "filepath": "../_audio/R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.45).mp3",
    "filename": "R.A. the Rugged Man - 3 Kingz (feat. Kool G Rap) (0.00 - 0.45).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 45.0,
    "artist": "R.A. the Rugged Man",
    "title": "3 Kingz (feat. Kool G Rap)",
    "timestamp": "2026-05-31 18:05:24"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Glass Card \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "filename": "Glass Card \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "kind": "video",
    "template": "glass_card",
    "platform": "vertical_full",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:05:20"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:05:20"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Cinematic \u22c5 Deicide - They Are the Children of the Underworld (0.50 - 1.20) [smoke_test].mp4",
    "filename": "Cinematic \u22c5 Deicide - They Are the Children of the Underworld (0.50 - 1.20) [smoke_test].mp4",
    "kind": "video",
    "template": "cinematic",
    "platform": "youtube",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:05:15"
  },
  {
    "filepath": "../_audio/Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "filename": "Deicide - They Are the Children of the Underworld (0.00 - 0.30).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 30.0,
    "artist": "Deicide",
    "title": "They Are the Children of the Underworld",
    "timestamp": "2026-05-31 18:05:15"
  },
  {
    "filepath": "../tests/videos/ffmpeg/Artist Focus \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "filename": "Artist Focus \u22c5 Juggaknots - Trouble Man (2.41 - 3.06) [smoke_test].mp4",
    "kind": "video",
    "template": "artist_focus",
    "platform": "vertical_full",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:05:12"
  },
  {
    "filepath": "../_audio/Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "filename": "Juggaknots - Trouble Man (0.00 - 0.25).mp3",
    "kind": "audio",
    "template": "clipped_audio",
    "platform": "default",
    "start": 0,
    "end": 25.000249,
    "artist": "Juggaknots",
    "title": "Trouble Man",
    "timestamp": "2026-05-31 18:05:12"
  }
];
