import type { ElementCategory, ElementDefinition } from "./types";

const registry: ElementDefinition[] = [
  // ── Text ──────────────────────────────────────────────────────────────────
  {
    id: "text",
    label: "Text",
    category: "text",
    tier: "core",
    implemented: true,
    component: "TextElement",
    description: "Styled text with reveal animations and typography presets",
    recommendedFor: ["clean", "cinematic", "editorial"],
    defaultIntensity: "medium",
    safeByDefault: true,
  },
  {
    id: "lyrics",
    label: "Lyrics",
    category: "text",
    tier: "core",
    implemented: true,
    component: "LyricsElement",
    description: "Synced lyrics display with karaoke and stacked modes",
    recommendedFor: ["story", "art_focus", "gallery"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "text-3d",
    label: "3D Text",
    category: "text",
    tier: "experimental",
    implemented: false,
    component: "Text3D",
    description: "Three.js extruded text with bevel and material",
    recommendedFor: [],
    avoidFor: ["clean", "minimal", "editorial"],
    defaultIntensity: "medium",
    audioReactive: true,
    requires3D: true,
    safeByDefault: false,
  },

  // ── Visualizers ───────────────────────────────────────────────────────────
  {
    id: "waveform",
    label: "Waveform",
    category: "visualizers",
    tier: "core",
    implemented: false,
    component: "Waveform",
    description: "Bar waveform visualizer for frequency amplitude",
    recommendedFor: ["clean", "cinematic", "vinyl"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "spectre",
    label: "Spectre",
    category: "visualizers",
    tier: "core",
    implemented: true,
    component: "SpectrumBars",
    description: "Full frequency spectrum bar display",
    recommendedFor: ["vhs", "concert", "club"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "oscilloscope",
    label: "Oscilloscope",
    category: "visualizers",
    tier: "core",
    implemented: true,
    component: "Oscilloscope",
    description: "Audio waveform trace like an oscilloscope",
    recommendedFor: ["vhs", "black-metal", "industrial"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "pulsar",
    label: "Pulsar",
    category: "visualizers",
    tier: "core",
    implemented: true,
    component: "Pulsar",
    description: "Audio-reactive concentric ring pulses",
    recommendedFor: ["boom-bap", "concert", "club"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "circle",
    label: "Circle",
    category: "visualizers",
    tier: "core",
    implemented: true,
    component: "RadialBars",
    description: "Circular / radial audio geometry",
    recommendedFor: ["luxury-vinyl", "cinematic"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "ferro-fluid",
    label: "Ferro Fluid",
    category: "visualizers",
    tier: "experimental",
    implemented: true,
    component: "FerroFluid",
    description: "Audio-reactive blob field with organic morphing using SVG blob primitives driven by frequency bands",
    recommendedFor: ["experimental", "electronic"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: false,
  },

  // ── Effects / Glow ────────────────────────────────────────────────────────
  {
    id: "bloom",
    label: "Bloom",
    category: "effects",
    tier: "premium",
    implemented: true,
    component: "Bloom",
    description: "2D bloom overlay with threshold and intensity control",
    recommendedFor: ["cinematic", "luxury-vinyl", "concert"],
    avoidFor: ["clean", "black-metal"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "unreal-bloom",
    label: "Unreal Bloom",
    category: "effects",
    tier: "premium",
    implemented: false,
    component: "UnrealBloom",
    description: "Three.js postprocessing bloom (requires enable3D)",
    recommendedFor: [],
    avoidFor: ["clean", "editorial"],
    defaultIntensity: "subtle",
    requires3D: true,
    requiresPostprocessing: true,
    safeByDefault: false,
  },
  {
    id: "strobe",
    label: "Strobe",
    category: "effects",
    tier: "disabled",
    implemented: true,
    component: "Strobe",
    description: "Frame-interval flash effect — disabled by policy, implemented but blocked from rendering",
    recommendedFor: [],
    avoidFor: ["clean", "cinematic", "editorial"],
    defaultIntensity: "heavy",
    audioReactive: true,
    safeByDefault: false,
  },

  // ── Effects / Color ───────────────────────────────────────────────────────
  {
    id: "brightness-contrast",
    label: "Brightness / Contrast",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "BrightnessContrast",
    description: "CSS-based brightness and contrast adjustment",
    recommendedFor: ["all"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "hue-saturation",
    label: "Hue / Saturation",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "HueSaturation",
    description: "Hue rotation and saturation adjustment",
    recommendedFor: ["all"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "color-grading",
    label: "Color Grading",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "ColorGrading",
    description: "Full color grade controls: exposure, contrast, temperature",
    recommendedFor: ["all"],
    defaultIntensity: "medium",
    safeByDefault: true,
  },
  {
    id: "filter-effect",
    label: "Filter",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "FilterEffect",
    description: "CSS filter presets: grayscale, sepia, blur, drop-shadow",
    recommendedFor: ["vhs", "black-metal"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "tone-mapping",
    label: "Tone Mapping",
    category: "effects",
    tier: "premium",
    implemented: false,
    component: "ToneMapping",
    description: "ACES / Reinhard tone mapping (requires postprocessing)",
    recommendedFor: [],
    requiresPostprocessing: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },
  {
    id: "black-white",
    label: "Black & White",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "BlackWhite",
    description: "Grayscale desaturation with optional contrast boost",
    recommendedFor: ["black-metal", "neo-noir"],
    defaultIntensity: "medium",
    safeByDefault: true,
  },
  {
    id: "inversion",
    label: "Inversion",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "Inversion",
    description: "CSS invert filter for negative image effect",
    recommendedFor: ["experimental"],
    avoidFor: ["clean", "editorial"],
    defaultIntensity: "medium",
    safeByDefault: false,
  },

  // ── Effects / Texture ─────────────────────────────────────────────────────
  {
    id: "noise",
    label: "Noise",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "Noise",
    description: "Procedural film grain / noise overlay",
    recommendedFor: ["vhs", "black-metal", "cinematic"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "scanline",
    label: "Scanline",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "Scanline",
    description: "CRT scanline overlay pattern",
    recommendedFor: ["vhs", "black-metal"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "vhs",
    label: "VHS",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "VHS",
    description: "VHS distortion: chromatic aberration, tears, tracking",
    recommendedFor: ["vhs-death", "metal-vhs"],
    avoidFor: ["clean", "cinematic", "luxury-vinyl"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: false,
  },
  {
    id: "pixelation",
    label: "Pixelation",
    category: "effects",
    tier: "experimental",
    implemented: true,
    component: "Pixelation",
    description: "CSS pixelation / mosaic block effect using backdrop-filter blur and block grid overlay",
    recommendedFor: ["vhs", "black-metal", "experimental"],
    defaultIntensity: "subtle",
    audioReactive: true,
    safeByDefault: false,
  },

  // ── Effects / Lens ────────────────────────────────────────────────────────
  {
    id: "vignette",
    label: "Vignette",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "Vignette",
    description: "Radial darkening overlay with lifted blacks",
    recommendedFor: ["all"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "chromatic-aberration",
    label: "Chromatic Aberration",
    category: "effects",
    tier: "core",
    implemented: true,
    component: "ChromaticAberration",
    description: "RGB channel offset for lens dispersion",
    recommendedFor: ["vhs", "black-metal", "experimental"],
    avoidFor: ["clean", "editorial"],
    defaultIntensity: "subtle",
    audioReactive: true,
    safeByDefault: false,
  },
  {
    id: "fisheye",
    label: "Fisheye",
    category: "effects",
    tier: "experimental",
    implemented: true,
    component: "Fisheye",
    description: "2D CSS/SVG fisheye warp effect",
    recommendedFor: ["experimental"],
    avoidFor: ["clean", "cinematic"],
    defaultIntensity: "subtle",
    safeByDefault: false,
  },

  // ── Depth Effects ─────────────────────────────────────────────────────────
  {
    id: "fog",
    label: "Fog",
    category: "depth",
    tier: "core",
    implemented: true,
    component: "DepthFog",
    description: "Atmospheric fog overlay with drift animation",
    recommendedFor: ["cinematic", "neo-noir", "black-metal"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "depth-blur",
    label: "Depth Blur",
    category: "depth",
    tier: "core",
    implemented: true,
    component: "DepthBlur",
    description: "Background blur with foreground focus for depth illusion",
    recommendedFor: ["cinematic", "editorial"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "ssao",
    label: "SSAO",
    category: "depth",
    tier: "experimental",
    implemented: false,
    component: "SSAO",
    description: "Screen-space ambient occlusion (requires 3D context)",
    recommendedFor: [],
    avoidFor: ["all-2d"],
    requires3D: true,
    requiresPostprocessing: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },

  // ── Shapes & 3D ──────────────────────────────────────────────────────────
  {
    id: "time-display",
    label: "Time Display",
    category: "shapes3d",
    tier: "core",
    implemented: true,
    component: "TimeDisplay3D",
    description: "Elapsed/remaining time or BPM counter overlay",
    recommendedFor: ["concert", "club", "vhs"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "box-3d",
    label: "Box",
    category: "shapes3d",
    tier: "experimental",
    implemented: false,
    component: "Box3D",
    description: "Three.js audio-reactive box mesh",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: false,
  },
  {
    id: "sparkles-3d",
    label: "Sparkles",
    category: "shapes3d",
    tier: "experimental",
    implemented: false,
    component: "Sparkles3D",
    description: "Drei Sparkles particle system (requires enable3D)",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },
  {
    id: "fog-3d",
    label: "Fog",
    category: "shapes3d",
    tier: "experimental",
    implemented: false,
    component: "Fog3D",
    description: "Three.js fog density effect (requires 3D scene)",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },

  // ── Backgrounds ──────────────────────────────────────────────────────────
  {
    id: "shader-bg",
    label: "Shader Background",
    category: "backgrounds",
    tier: "premium",
    implemented: true,
    component: "ShaderBackground",
    description: "GLSL shader backgrounds: plasma, liquid, metal, smoke, warp",
    recommendedFor: ["concert", "club", "experimental"],
    defaultIntensity: "medium",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "gradient-bg",
    label: "Gradient",
    category: "backgrounds",
    tier: "core",
    implemented: true,
    component: "GradientBackground",
    description: "Palette-aware gradient background with radial blooms",
    recommendedFor: ["all"],
    defaultIntensity: "medium",
    safeByDefault: true,
  },
  {
    id: "noise-bg",
    label: "Noise Background",
    category: "backgrounds",
    tier: "core",
    implemented: true,
    component: "NoiseBackground",
    description: "Animated noise texture background",
    recommendedFor: ["vhs", "black-metal"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "video-sphere",
    label: "Video Sphere",
    category: "backgrounds",
    tier: "experimental",
    implemented: false,
    component: "VideoSphere",
    description: "Three.js video sphere / equirectangular background",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },

  // ── Lights ────────────────────────────────────────────────────────────────
  {
    id: "ambient-light",
    label: "Ambient Light",
    category: "lights",
    tier: "core",
    implemented: true,
    component: "AmbientLightLayer",
    description: "Ambient color wash using gradient overlay",
    recommendedFor: ["all"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "point-light",
    label: "Point Light",
    category: "lights",
    tier: "experimental",
    implemented: true,
    component: "PointLightLayer",
    description: "Radial spotlight overlay from a single point",
    recommendedFor: ["cinematic", "neo-noir"],
    defaultIntensity: "subtle",
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "light-preset",
    label: "Light Preset",
    category: "lights",
    tier: "premium",
    implemented: true,
    component: "LightPreset",
    description: "Pre-configured lighting setups: warm-glow, cool-rim, golden-hour, neon-tunnel, studio",
    recommendedFor: ["cinematic", "neo-noir", "concert"],
    defaultIntensity: "subtle",
    safeByDefault: true,
  },
  {
    id: "spot-light",
    label: "Spot Light",
    category: "lights",
    tier: "experimental",
    implemented: false,
    component: "SpotLightLayer",
    description: "Three.js spot light (requires enable3D)",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },
  {
    id: "directional-light",
    label: "Directional Light",
    category: "lights",
    tier: "experimental",
    implemented: false,
    component: "DirectionalLightLayer",
    description: "Three.js directional light (requires enable3D)",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },

  // ── Scene ─────────────────────────────────────────────────────────────────
  {
    id: "camera-3d",
    label: "Camera",
    category: "scene",
    tier: "experimental",
    implemented: false,
    component: "Camera3D",
    description: "Three.js camera controller: drift, orbit, handheld",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },
  {
    id: "environment-3d",
    label: "Environment",
    category: "scene",
    tier: "experimental",
    implemented: false,
    component: "EnvironmentLayer",
    description: "Drei environment map and scene lighting",
    recommendedFor: [],
    requires3D: true,
    defaultIntensity: "medium",
    safeByDefault: false,
  },
];

export default registry;
