import type { ElementCategory, ElementDefinition } from "./types";
import { defaultSections } from "./inspector";

const registry: ElementDefinition[] = [
  // ── Text ──────────────────────────────────────────────────────────────────
  {
    id: "text",
    label: "Text",
    category: "text",
    group: "Typography",
    tier: "core",
    implemented: true,
    component: "TextElement",
    description: "Styled text with reveal animations and typography presets",
    inspector: [
      ...defaultSections,
      {
        title: "Text",
        controls: [
          { type: "select", key: "preset", label: "Style", options: ["cinematic", "minimal", "brutal", "mono"], defaultValue: "cinematic", keyframeable: false },
          { type: "select", key: "reveal", label: "Reveal", options: ["none", "fade-up", "track-in", "mask"], defaultValue: "fade-up", keyframeable: false },
          { type: "select", key: "align", label: "Align", options: ["left", "center", "right"], defaultValue: "center", keyframeable: false },
          { type: "color", key: "textColor", label: "Text Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "fontSize", label: "Size", min: 12, max: 120, step: 1, defaultValue: 48, keyframeable: true },
        ],
      },
    ],
    defaultProps: { preset: "cinematic", reveal: "fade-up", align: "center", textColor: "#FFFFFF", fontSize: 48 },
    recommendedFor: ["clean", "cinematic", "editorial"],
    safeByDefault: true,
  },
  {
    id: "lyrics",
    label: "Lyrics",
    category: "text",
    group: "Typography",
    tier: "core",
    implemented: true,
    component: "LyricsElement",
    description: "Synced lyrics display with karaoke and stacked modes",
    inspector: [
      ...defaultSections,
      {
        title: "Lyrics",
        controls: [
          { type: "select", key: "mode", label: "Mode", options: ["plain", "karaoke", "stacked", "lower-third"], defaultValue: "plain", keyframeable: false },
          { type: "color", key: "textColor", label: "Text Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "fontSize", label: "Font Size", min: 12, max: 72, step: 1, defaultValue: 28, keyframeable: true },
        ],
      },
    ],
    defaultProps: { mode: "plain", textColor: "#FFFFFF", fontSize: 28 },
    recommendedFor: ["story", "art_focus", "gallery"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "text-3d",
    label: "3D Text",
    category: "text",
    group: "Typography",
    tier: "experimental",
    implemented: false,
    component: "Text3D",
    description: "Three.js extruded text with bevel and material",
    inspector: [
      ...defaultSections,
      {
        title: "3D Text",
        controls: [
          { type: "color", key: "textColor", label: "Text Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "metalness", label: "Metalness", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
          { type: "slider", key: "roughness", label: "Roughness", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
        ],
      },
    ],
    defaultProps: { textColor: "#FFFFFF", metalness: 0.5, roughness: 0.3 },
    recommendedFor: [],
    avoidFor: ["clean", "minimal", "editorial"],
    requires3D: true,
    safeByDefault: false,
  },

  // ── Visualizers ───────────────────────────────────────────────────────────
  {
    id: "waveform",
    label: "Waveform",
    category: "visualizers",
    group: "Wave",
    tier: "core",
    implemented: true,
    component: "WaveRibbon",
    description: "Audio waveform trace for amplitude visualization",
    inspector: [
      ...defaultSections,
      {
        title: "Waveform",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "thickness", label: "Thickness", min: 0.5, max: 10, step: 0.5, defaultValue: 3, keyframeable: true },
          { type: "slider", key: "samples", label: "Samples", min: 8, max: 128, step: 1, defaultValue: 20, keyframeable: true },
          { type: "slider", key: "smoothing", label: "Smoothing", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
          { type: "boolean", key: "mirror", label: "Mirror", defaultValue: false, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#FFFFFF", thickness: 3, samples: 20, smoothing: 0.5, mirror: false },
    recommendedFor: ["clean", "cinematic", "vinyl"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "spectre",
    label: "Spectre",
    category: "visualizers",
    group: "Wave",
    tier: "core",
    implemented: true,
    component: "SpectrumBars",
    description: "Full frequency spectrum bar display",
    inspector: [
      ...defaultSections,
      {
        title: "Spectre",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "count", label: "Bars", min: 8, max: 128, step: 1, defaultValue: 48, keyframeable: true },
          { type: "boolean", key: "mirror", label: "Mirror", defaultValue: false, keyframeable: true },
          { type: "boolean", key: "glow", label: "Glow", defaultValue: false, keyframeable: false },
        ],
      },
    ],
    defaultProps: { color: "#FFFFFF", count: 48, mirror: false, glow: false },
    recommendedFor: ["vhs", "concert", "club"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "oscilloscope",
    label: "Oscilloscope",
    category: "visualizers",
    group: "Wave",
    tier: "core",
    implemented: true,
    component: "Oscilloscope",
    description: "Audio waveform trace like an oscilloscope",
    inspector: [
      ...defaultSections,
      {
        title: "Oscilloscope",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "strokeWidth", label: "Stroke Width", min: 0.5, max: 10, step: 0.5, defaultValue: 3, keyframeable: true },
          { type: "boolean", key: "glow", label: "Glow", defaultValue: false, keyframeable: false },
        ],
      },
    ],
    defaultProps: { color: "#FFFFFF", strokeWidth: 3, glow: false },
    recommendedFor: ["vhs", "black-metal", "industrial"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "pulsar",
    label: "Pulsar",
    category: "visualizers",
    group: "Pulse",
    tier: "core",
    implemented: true,
    component: "PulseRings",
    description: "Audio-reactive concentric ring pulses",
    inspector: [
      ...defaultSections,
      {
        title: "Pulsar",
        controls: [
          { type: "color", key: "primaryColor", label: "Primary color", defaultValue: "#274B82", keyframeable: true },
          { type: "color", key: "secondaryColor", label: "Secondary color", defaultValue: "#FF00FF", keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 3, step: 0.01, defaultValue: 1.9, keyframeable: true },
          { type: "slider", key: "density", label: "Density", min: 0, max: 5, step: 0.01, defaultValue: 2.6, keyframeable: true },
          { type: "slider", key: "pattern", label: "Pattern", min: 0, max: 24, step: 1, defaultValue: 12, keyframeable: true },
          { type: "slider", key: "volume", label: "Volume", min: 0, max: 10, step: 0.01, defaultValue: 2.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { primaryColor: "#274B82", secondaryColor: "#FF00FF", intensity: 1.9, density: 2.6, pattern: 12, volume: 2.5 },
    recommendedFor: ["boom-bap", "concert", "club"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "circle",
    label: "Circle",
    category: "visualizers",
    group: "Pulse",
    tier: "core",
    implemented: true,
    component: "RadialBars",
    description: "Circular / radial audio geometry",
    inspector: [
      ...defaultSections,
      {
        title: "Circle",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "select", key: "mode", label: "Mode", options: ["ring", "flower"], defaultValue: "ring", keyframeable: false },
          { type: "slider", key: "count", label: "Bars", min: 8, max: 128, step: 1, defaultValue: 64, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#FFFFFF", mode: "ring", count: 64 },
    recommendedFor: ["luxury-vinyl", "cinematic"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "ferro-fluid",
    label: "Ferro Fluid",
    category: "visualizers",
    group: "Pulse",
    tier: "experimental",
    implemented: true,
    component: "FerroFluid",
    description: "Audio-reactive blob field with organic morphing using SVG blob primitives driven by frequency bands",
    inspector: [
      ...defaultSections,
      {
        title: "Ferro Fluid",
        controls: [
          { type: "color", key: "primaryColor", label: "Primary color", defaultValue: "#6bcbff", keyframeable: true },
          { type: "color", key: "secondaryColor", label: "Secondary color", defaultValue: "#a66cff", keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 2, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { primaryColor: "#6bcbff", secondaryColor: "#a66cff", intensity: 0.5 },
    recommendedFor: ["experimental", "electronic"],
    audioReactive: true,
    safeByDefault: false,
  },

  // ── Effects / Glow ────────────────────────────────────────────────────────
  {
    id: "bloom",
    label: "Bloom",
    category: "effects",
    group: "Glow",
    tier: "premium",
    implemented: true,
    component: "Bloom",
    description: "2D bloom overlay with threshold and intensity control",
    inspector: [
      ...defaultSections,
      {
        title: "Bloom",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 3, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "luminanceThreshold", label: "Luminance Threshold", min: 0, max: 1, step: 0.001, defaultValue: 0.9, keyframeable: true },
          { type: "slider", key: "luminanceSmoothing", label: "Luminance Smoothing", min: 0, max: 1, step: 0.001, defaultValue: 0.025, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0, luminanceThreshold: 0.9, luminanceSmoothing: 0.025 },
    recommendedFor: ["cinematic", "luxury-vinyl", "concert"],
    avoidFor: ["clean", "black-metal"],
    safeByDefault: true,
  },
  {
    id: "unreal-bloom",
    label: "Unreal Bloom",
    category: "effects",
    group: "Glow",
    tier: "premium",
    implemented: false,
    component: "UnrealBloom",
    description: "Three.js postprocessing bloom (requires enable3D) — currently mapped to closest available 2D bloom approximation",
    inspector: [
      ...defaultSections,
      {
        title: "Unreal Bloom",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 5, step: 0.01, defaultValue: 1.5, keyframeable: true },
          { type: "slider", key: "luminanceThreshold", label: "Luminance Threshold", min: 0, max: 1, step: 0.001, defaultValue: 0.85, keyframeable: true },
          { type: "slider", key: "luminanceSmoothing", label: "Luminance Smoothing", min: 0, max: 1, step: 0.001, defaultValue: 0.025, keyframeable: true },
          { type: "slider", key: "radius", label: "Radius", min: 0, max: 1, step: 0.01, defaultValue: 0.4, keyframeable: true },
          { type: "slider", key: "levels", label: "Levels", min: 1, max: 10, step: 1, defaultValue: 5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 1.5, luminanceThreshold: 0.85, luminanceSmoothing: 0.025, radius: 0.4, levels: 5 },
    recommendedFor: [],
    avoidFor: ["clean", "editorial"],
    requires3D: true,
    requiresPostprocessing: true,
    safeByDefault: false,
  },
  {
    id: "strobe",
    label: "Strobe",
    category: "effects",
    group: "Glow",
    tier: "disabled",
    implemented: true,
    component: "Strobe",
    description: "Frame-interval flash effect — disabled by policy, explicit opt-in required",
    inspector: [
      {
        title: "Strobe",
        controls: [
          { type: "slider", key: "frequency", label: "Frequency", min: 0, max: 10, step: 0.01, defaultValue: 0.25, keyframeable: true },
          { type: "slider", key: "duration", label: "Duration", min: 0, max: 2, step: 0.01, defaultValue: 0.25, keyframeable: true },
          { type: "slider", key: "opacity", label: "Opacity", min: 0, max: 1, step: 0.01, defaultValue: 1, keyframeable: true },
          { type: "color", key: "color", label: "Color", defaultValue: "#FFFFFF", keyframeable: true },
        ],
      },
    ],
    defaultProps: { frequency: 0.25, duration: 0.25, opacity: 1, color: "#FFFFFF" },
    recommendedFor: [],
    avoidFor: ["clean", "cinematic", "editorial"],
    audioReactive: true,
    safeByDefault: false,
  },

  // ── Effects / Color ───────────────────────────────────────────────────────
  {
    id: "brightness-contrast",
    label: "Brightness / Contrast",
    category: "effects",
    group: "Color",
    tier: "core",
    implemented: true,
    component: "BrightnessContrast",
    description: "CSS-based brightness and contrast adjustment",
    inspector: [
      ...defaultSections,
      {
        title: "Brightness / Contrast",
        controls: [
          { type: "slider", key: "brightness", label: "Brightness", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "contrast", label: "Contrast", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
        ],
      },
    ],
    defaultProps: { brightness: 0, contrast: 0 },
    recommendedFor: ["all"],
    safeByDefault: true,
  },
  {
    id: "hue-saturation",
    label: "Hue / Saturation",
    category: "effects",
    group: "Color",
    tier: "core",
    implemented: true,
    component: "HueSaturation",
    description: "Hue rotation and saturation adjustment",
    inspector: [
      ...defaultSections,
      {
        title: "Hue / Saturation",
        controls: [
          { type: "slider", key: "hue", label: "Hue", min: -180, max: 180, step: 1, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "saturation", label: "Saturation", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
        ],
      },
    ],
    defaultProps: { hue: 0, saturation: 0 },
    recommendedFor: ["all"],
    safeByDefault: true,
  },
  {
    id: "color-grading",
    label: "Color Grading",
    category: "effects",
    group: "Color",
    tier: "core",
    implemented: true,
    component: "ColorGrading",
    description: "Full color grade controls: exposure, contrast, temperature, tint, shadows, blacks, midtones, vibrance",
    inspector: [
      ...defaultSections,
      {
        title: "Color Grading",
        controls: [
          { type: "slider", key: "temperature", label: "Temperature", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "tint", label: "Tint", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "exposure", label: "Exposure", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "shadows", label: "Shadows", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "blacks", label: "Blacks", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "midtones", label: "Midtones", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "vibrance", label: "Vibrance", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
        ],
      },
    ],
    defaultProps: { temperature: 0, tint: 0, exposure: 0, shadows: 0, blacks: 0, midtones: 0, vibrance: 0 },
    recommendedFor: ["all"],
    safeByDefault: true,
  },
  {
    id: "filter-effect",
    label: "Filter",
    category: "effects",
    group: "Color",
    tier: "core",
    implemented: true,
    component: "FilterEffect",
    description: "CSS filter presets: grayscale, sepia, blur, drop-shadow",
    inspector: [
      ...defaultSections,
      {
        title: "Filter",
        controls: [
          { type: "select", key: "filterType", label: "Type", options: ["grayscale", "sepia", "blur", "drop-shadow"], defaultValue: "grayscale", keyframeable: false },
          { type: "slider", key: "amount", label: "Amount", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { filterType: "grayscale", amount: 0.5 },
    recommendedFor: ["vhs", "black-metal"],
    safeByDefault: true,
  },
  {
    id: "tone-mapping",
    label: "Tone Mapping",
    category: "effects",
    group: "Color",
    tier: "premium",
    implemented: false,
    component: "ToneMapping",
    description: "ACES / Reinhard tone mapping (requires postprocessing)",
    inspector: [
      ...defaultSections,
      {
        title: "Tone Mapping",
        controls: [
          { type: "select", key: "algorithm", label: "Algorithm", options: ["aces", "reinhard", "filmic"], defaultValue: "aces", keyframeable: false },
          { type: "slider", key: "exposure", label: "Exposure", min: -2, max: 2, step: 0.01, defaultValue: 0, keyframeable: true },
        ],
      },
    ],
    defaultProps: { algorithm: "aces", exposure: 0 },
    recommendedFor: [],
    requiresPostprocessing: true,
    safeByDefault: false,
  },
  {
    id: "black-white",
    label: "Black & White",
    category: "effects",
    group: "Color",
    tier: "core",
    implemented: true,
    component: "BlackWhite",
    description: "Grayscale desaturation with optional contrast boost",
    inspector: [
      ...defaultSections,
      {
        title: "Black & White",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "contrast", label: "Contrast Boost", min: -1, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 1, contrast: 0 },
    recommendedFor: ["black-metal", "neo-noir"],
    safeByDefault: true,
  },
  {
    id: "inversion",
    label: "Inversion",
    category: "effects",
    group: "Color",
    tier: "core",
    implemented: true,
    component: "Inversion",
    description: "CSS invert filter for negative image effect",
    inspector: [
      ...defaultSections,
      {
        title: "Inversion",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.5 },
    recommendedFor: ["experimental"],
    avoidFor: ["clean", "editorial"],
    safeByDefault: false,
  },

  // ── Effects / Texture ─────────────────────────────────────────────────────
  {
    id: "noise",
    label: "Noise",
    category: "effects",
    group: "Texture",
    tier: "core",
    implemented: true,
    component: "Noise",
    description: "Procedural film grain / noise overlay",
    inspector: [
      ...defaultSections,
      {
        title: "Noise",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
          { type: "slider", key: "speed", label: "Animation Speed", min: 0, max: 2, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.3, speed: 0.5 },
    recommendedFor: ["vhs", "black-metal", "cinematic"],
    safeByDefault: true,
  },
  {
    id: "scanline",
    label: "Scanline",
    category: "effects",
    group: "Texture",
    tier: "core",
    implemented: true,
    component: "Scanline",
    description: "CRT scanline overlay pattern",
    inspector: [
      ...defaultSections,
      {
        title: "Scanline",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
          { type: "slider", key: "lineWidth", label: "Line Width", min: 0.5, max: 4, step: 0.5, defaultValue: 2, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.3, lineWidth: 2 },
    recommendedFor: ["vhs", "black-metal"],
    safeByDefault: true,
  },
  {
    id: "vhs",
    label: "VHS",
    category: "effects",
    group: "Texture",
    tier: "core",
    implemented: true,
    component: "VHS",
    description: "VHS distortion: chromatic aberration, tears, tracking",
    inspector: [
      ...defaultSections,
      {
        title: "VHS",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
          { type: "slider", key: "tearCount", label: "Tear Count", min: 0, max: 20, step: 1, defaultValue: 3, keyframeable: true },
          { type: "slider", key: "trackingJitter", label: "Tracking Jitter", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.5, tearCount: 3, trackingJitter: 0.3 },
    recommendedFor: ["vhs-death", "metal-vhs"],
    avoidFor: ["clean", "cinematic", "luxury-vinyl"],
    audioReactive: true,
    safeByDefault: false,
  },
  {
    id: "pixelation",
    label: "Pixelation",
    category: "effects",
    group: "Texture",
    tier: "experimental",
    implemented: true,
    component: "Pixelation",
    description: "CSS pixelation / mosaic block effect using backdrop-filter blur and block grid overlay",
    inspector: [
      ...defaultSections,
      {
        title: "Pixelation",
        controls: [
          { type: "slider", key: "blockSize", label: "Block Size", min: 2, max: 50, step: 1, defaultValue: 8, keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { blockSize: 8, intensity: 0.5 },
    recommendedFor: ["vhs", "black-metal", "experimental"],
    audioReactive: true,
    safeByDefault: false,
  },

  // ── Effects / Lens ────────────────────────────────────────────────────────
  {
    id: "vignette",
    label: "Vignette",
    category: "effects",
    group: "Lens",
    tier: "core",
    implemented: true,
    component: "Vignette",
    description: "Radial darkening overlay with lifted blacks",
    inspector: [
      ...defaultSections,
      {
        title: "Vignette",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
          { type: "slider", key: "feather", label: "Feather", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.5, feather: 0.5 },
    recommendedFor: ["all"],
    safeByDefault: true,
  },
  {
    id: "chromatic-aberration",
    label: "Chromatic Aberration",
    category: "effects",
    group: "Lens",
    tier: "core",
    implemented: true,
    component: "ChromaticAberration",
    description: "RGB channel offset for lens dispersion",
    inspector: [
      ...defaultSections,
      {
        title: "Chromatic Aberration",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
          { type: "slider", key: "angle", label: "Angle", min: 0, max: 360, step: 1, defaultValue: 0, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.3, angle: 0 },
    recommendedFor: ["vhs", "black-metal", "experimental"],
    avoidFor: ["clean", "editorial"],
    audioReactive: true,
    safeByDefault: false,
  },
  {
    id: "fisheye",
    label: "Fisheye",
    category: "effects",
    group: "Lens",
    tier: "experimental",
    implemented: true,
    component: "Fisheye",
    description: "2D CSS/SVG fisheye warp effect",
    inspector: [
      ...defaultSections,
      {
        title: "Fisheye",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
          { type: "slider", key: "zoom", label: "Zoom", min: 0.5, max: 2, step: 0.01, defaultValue: 1, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.3, zoom: 1 },
    recommendedFor: ["experimental"],
    avoidFor: ["clean", "cinematic"],
    safeByDefault: false,
  },

  // ── Depth Effects ─────────────────────────────────────────────────────────
  {
    id: "fog",
    label: "Fog",
    category: "depth",
    group: "Atmosphere",
    tier: "core",
    implemented: true,
    component: "DepthFog",
    description: "Atmospheric fog overlay with drift animation",
    inspector: [
      ...defaultSections,
      {
        title: "Fog",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
          { type: "color", key: "color", label: "Color", defaultValue: "#000000", keyframeable: true },
          { type: "slider", key: "density", label: "Density", min: 0, max: 2, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.3, color: "#000000", density: 0.5 },
    recommendedFor: ["cinematic", "neo-noir", "black-metal"],
    safeByDefault: true,
  },
  {
    id: "depth-blur",
    label: "Depth Blur",
    category: "depth",
    group: "Atmosphere",
    tier: "core",
    implemented: true,
    component: "DepthBlur",
    description: "Background blur with foreground focus for depth illusion",
    inspector: [
      ...defaultSections,
      {
        title: "Depth Blur",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
          { type: "slider", key: "focus", label: "Focus Position", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.3, focus: 0.5 },
    recommendedFor: ["cinematic", "editorial"],
    safeByDefault: true,
  },
  {
    id: "ssao",
    label: "SSAO",
    category: "depth",
    group: "Atmosphere",
    tier: "experimental",
    implemented: false,
    component: "SSAO",
    description: "Screen-space ambient occlusion (requires 3D context)",
    inspector: [
      ...defaultSections,
      {
        title: "SSAO",
        controls: [
          { type: "slider", key: "radius", label: "Radius", min: 0, max: 5, step: 0.01, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 2, step: 0.01, defaultValue: 0.5, keyframeable: true },
          { type: "slider", key: "bias", label: "Bias", min: 0, max: 1, step: 0.001, defaultValue: 0.025, keyframeable: true },
        ],
      },
    ],
    defaultProps: { radius: 1, intensity: 0.5, bias: 0.025 },
    recommendedFor: [],
    avoidFor: ["all-2d"],
    requires3D: true,
    requiresPostprocessing: true,
    safeByDefault: false,
  },

  // ── Shapes & 3D ──────────────────────────────────────────────────────────
  {
    id: "time-display",
    label: "Time Display",
    category: "shapes3d",
    group: "Overlay",
    tier: "core",
    implemented: true,
    component: "TimeDisplay3D",
    description: "Elapsed/remaining time or BPM counter overlay — 2D version",
    inspector: [
      ...defaultSections,
      {
        title: "Time Display",
        controls: [
          { type: "boolean", key: "reverse", label: "Reverse", defaultValue: false, keyframeable: false },
          { type: "boolean", key: "relative", label: "Relative", defaultValue: false, keyframeable: false },
          { type: "select", key: "timeFormat", label: "Time format", options: ["MM:SS", "M:SS", "SS", "HH:MM:SS"], defaultValue: "MM:SS", keyframeable: false },
          { type: "select", key: "font", label: "Font", options: ["Inter", "Roboto", "Space Mono", "Oswald"], defaultValue: "Roboto", keyframeable: false },
          { type: "color", key: "textColor", label: "Text color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "metalness", label: "Metalness", min: 0, max: 1, step: 0.01, defaultValue: 0, keyframeable: true },
          { type: "slider", key: "roughness", label: "Roughness", min: 0, max: 1, step: 0.01, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "thickness", label: "Thickness", min: 0, max: 10, step: 0.01, defaultValue: 1, keyframeable: true },
          { type: "boolean", key: "outline", label: "Outline", defaultValue: false, keyframeable: true },
        ],
      },
    ],
    defaultProps: { reverse: false, relative: false, timeFormat: "MM:SS", font: "Roboto", textColor: "#FFFFFF", metalness: 0, roughness: 1, thickness: 1, outline: false },
    recommendedFor: ["concert", "club", "vhs"],
    safeByDefault: true,
  },
  {
    id: "box-3d",
    label: "Box",
    category: "shapes3d",
    group: "Geometry",
    tier: "experimental",
    implemented: false,
    component: "Box3D",
    description: "Three.js audio-reactive box mesh",
    inspector: [
      ...defaultSections,
      {
        title: "Box",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#FFFFFF", keyframeable: true },
          { type: "slider", key: "size", label: "Size", min: 0.1, max: 5, step: 0.1, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "metalness", label: "Metalness", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
          { type: "slider", key: "roughness", label: "Roughness", min: 0, max: 1, step: 0.01, defaultValue: 0.3, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#FFFFFF", size: 1, metalness: 0.5, roughness: 0.3 },
    recommendedFor: [],
    requires3D: true,
    audioReactive: true,
    safeByDefault: false,
  },
  {
    id: "sparkles-3d",
    label: "Sparkles",
    category: "shapes3d",
    group: "Geometry",
    tier: "experimental",
    implemented: false,
    component: "Sparkles3D",
    description: "Drei Sparkles particle system (requires enable3D)",
    inspector: [
      ...defaultSections,
      {
        title: "Sparkles",
        controls: [
          { type: "slider", key: "count", label: "Count", min: 10, max: 1000, step: 10, defaultValue: 100, keyframeable: true },
          { type: "slider", key: "speed", label: "Speed", min: 0, max: 5, step: 0.1, defaultValue: 1, keyframeable: true },
          { type: "color", key: "color", label: "Color", defaultValue: "#FFFFFF", keyframeable: true },
        ],
      },
    ],
    defaultProps: { count: 100, speed: 1, color: "#FFFFFF" },
    recommendedFor: [],
    requires3D: true,
    safeByDefault: false,
  },
  {
    id: "fog-3d",
    label: "Fog",
    category: "shapes3d",
    group: "Geometry",
    tier: "experimental",
    implemented: false,
    component: "Fog3D",
    description: "Three.js fog density effect (requires 3D scene)",
    inspector: [
      ...defaultSections,
      {
        title: "3D Fog",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#000000", keyframeable: true },
          { type: "slider", key: "density", label: "Density", min: 0, max: 1, step: 0.01, defaultValue: 0.1, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#000000", density: 0.1 },
    recommendedFor: [],
    requires3D: true,
    safeByDefault: false,
  },

  // ── Backgrounds ──────────────────────────────────────────────────────────
  {
    id: "shader-bg",
    label: "Shader Background",
    category: "backgrounds",
    group: "Dynamic",
    tier: "premium",
    implemented: true,
    component: "ShaderBackground",
    description: "Shader preset backgrounds: trip, space, fractals, shrooms, hyperloop",
    inspector: [
      ...defaultSections,
      {
        title: "Shader",
        controls: [
          { type: "select", key: "shaderPreset", label: "Shader", options: ["custom", "trip", "space", "fractals", "shrooms", "hyperloop"], defaultValue: "trip", keyframeable: false },
          { type: "color", key: "baseColor", label: "Base Color", defaultValue: "#FF00FF", keyframeable: true },
          { type: "color", key: "intensifyColor", label: "Intensify Color", defaultValue: "#9333EA", keyframeable: true },
          { type: "slider", key: "thickness", label: "Thickness", min: 0, max: 5, step: 0.01, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "pattern", label: "Pattern", min: 0, max: 2, step: 0.01, defaultValue: 0.7, keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 20, step: 0.01, defaultValue: 10, keyframeable: true },
        ],
      },
    ],
    defaultProps: { shaderPreset: "trip", baseColor: "#FF00FF", intensifyColor: "#9333EA", thickness: 1, pattern: 0.7, intensity: 10 },
    recommendedFor: ["concert", "club", "experimental"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "gradient-bg",
    label: "Gradient",
    category: "backgrounds",
    group: "Static",
    tier: "core",
    implemented: true,
    component: "GradientBackground",
    description: "Palette-aware gradient background with radial blooms",
    inspector: [
      ...defaultSections,
      {
        title: "Gradient",
        controls: [
          { type: "select", key: "direction", label: "Direction", options: ["vertical", "horizontal", "diagonal", "radial"], defaultValue: "vertical", keyframeable: false },
          { type: "color", key: "color1", label: "Color 1", defaultValue: "#0f0c29", keyframeable: true },
          { type: "color", key: "color2", label: "Color 2", defaultValue: "#302b63", keyframeable: true },
          { type: "color", key: "color3", label: "Color 3", defaultValue: "#24243e", keyframeable: true },
        ],
      },
    ],
    defaultProps: { direction: "vertical", color1: "#0f0c29", color2: "#302b63", color3: "#24243e" },
    recommendedFor: ["all"],
    safeByDefault: true,
  },
  {
    id: "noise-bg",
    label: "Noise Background",
    category: "backgrounds",
    group: "Static",
    tier: "core",
    implemented: true,
    component: "NoiseBackground",
    description: "Animated noise texture background",
    inspector: [
      ...defaultSections,
      {
        title: "Noise Background",
        controls: [
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.05, keyframeable: true },
          { type: "color", key: "color", label: "Color Tint", defaultValue: "#000000", keyframeable: true },
        ],
      },
    ],
    defaultProps: { intensity: 0.05, color: "#000000" },
    recommendedFor: ["vhs", "black-metal"],
    safeByDefault: true,
  },
  {
    id: "video-sphere",
    label: "Video Sphere",
    category: "backgrounds",
    group: "Dynamic",
    tier: "experimental",
    implemented: false,
    component: "VideoSphere",
    description: "Three.js video sphere / equirectangular background - does not load remote assets",
    inspector: [
      ...defaultSections,
      {
        title: "Video Sphere",
        controls: [
          { type: "select", key: "projection", label: "Projection", options: ["equirectangular", "cube-map"], defaultValue: "equirectangular", keyframeable: false },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 2, step: 0.01, defaultValue: 1, keyframeable: true },
        ],
      },
    ],
    defaultProps: { projection: "equirectangular", intensity: 1 },
    recommendedFor: [],
    requires3D: true,
    safeByDefault: false,
  },

  // ── Lights ────────────────────────────────────────────────────────────────
  {
    id: "ambient-light",
    label: "Ambient Light",
    category: "lights",
    group: "Fill",
    tier: "core",
    implemented: true,
    component: "AmbientLightLayer",
    description: "Ambient color wash using gradient overlay",
    inspector: [
      ...defaultSections,
      {
        title: "Ambient Light",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#ffaa44", keyframeable: true },
          { type: "slider", key: "spread", label: "Spread", min: 0, max: 100, step: 1, defaultValue: 50, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#ffaa44", spread: 50 },
    recommendedFor: ["all"],
    safeByDefault: true,
  },
  {
    id: "point-light",
    label: "Point Light",
    category: "lights",
    group: "Fill",
    tier: "experimental",
    implemented: true,
    component: "PointLightLayer",
    description: "Radial spotlight overlay from a single point",
    inspector: [
      ...defaultSections,
      {
        title: "Point Light",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#ffffff", keyframeable: true },
          { type: "slider", key: "radius", label: "Radius", min: 5, max: 100, step: 1, defaultValue: 30, keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.1, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#ffffff", radius: 30, intensity: 0.1 },
    recommendedFor: ["cinematic", "neo-noir"],
    audioReactive: true,
    safeByDefault: true,
  },
  {
    id: "light-preset",
    label: "Light Preset",
    category: "lights",
    group: "Fill",
    tier: "premium",
    implemented: true,
    component: "LightPreset",
    description: "Pre-configured lighting setups: warm-glow, cool-rim, golden-hour, neon-tunnel, studio",
    inspector: [
      ...defaultSections,
      {
        title: "Light Preset",
        controls: [
          { type: "select", key: "preset", label: "Preset", options: ["warm-glow", "cool-rim", "golden-hour", "neon-tunnel", "studio"], defaultValue: "warm-glow", keyframeable: false },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { preset: "warm-glow", intensity: 0.5 },
    recommendedFor: ["cinematic", "neo-noir", "concert"],
    safeByDefault: true,
  },
  {
    id: "spot-light",
    label: "Spot Light",
    category: "lights",
    group: "3D",
    tier: "experimental",
    implemented: false,
    component: "SpotLightLayer",
    description: "Three.js spot light (requires enable3D)",
    inspector: [
      ...defaultSections,
      {
        title: "Spot Light",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#ffffff", keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 5, step: 0.1, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "angle", label: "Angle", min: 0, max: 90, step: 1, defaultValue: 30, keyframeable: true },
          { type: "slider", key: "penumbra", label: "Penumbra", min: 0, max: 1, step: 0.01, defaultValue: 0.5, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#ffffff", intensity: 1, angle: 30, penumbra: 0.5 },
    recommendedFor: [],
    requires3D: true,
    safeByDefault: false,
  },
  {
    id: "directional-light",
    label: "Directional Light",
    category: "lights",
    group: "3D",
    tier: "experimental",
    implemented: false,
    component: "DirectionalLightLayer",
    description: "Three.js directional light (requires enable3D)",
    inspector: [
      ...defaultSections,
      {
        title: "Directional Light",
        controls: [
          { type: "color", key: "color", label: "Color", defaultValue: "#ffffff", keyframeable: true },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 5, step: 0.1, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "elevation", label: "Elevation", min: -90, max: 90, step: 1, defaultValue: 45, keyframeable: true },
          { type: "slider", key: "azimuth", label: "Azimuth", min: -180, max: 180, step: 1, defaultValue: 45, keyframeable: true },
        ],
      },
    ],
    defaultProps: { color: "#ffffff", intensity: 1, elevation: 45, azimuth: 45 },
    recommendedFor: [],
    requires3D: true,
    safeByDefault: false,
  },

  // ── Scene ─────────────────────────────────────────────────────────────────
  {
    id: "camera-3d",
    label: "Camera",
    category: "scene",
    group: "Controller",
    tier: "experimental",
    implemented: false,
    component: "Camera3D",
    description: "Three.js camera controller: drift, orbit, handheld",
    inspector: [
      ...defaultSections,
      {
        title: "Camera",
        controls: [
          { type: "select", key: "mode", label: "Mode", options: ["drift", "orbit", "handheld", "static"], defaultValue: "static", keyframeable: false },
          { type: "slider", key: "zoom", label: "Zoom", min: 0.1, max: 3, step: 0.01, defaultValue: 1, keyframeable: true },
          { type: "slider", key: "fov", label: "FOV", min: 10, max: 120, step: 1, defaultValue: 50, keyframeable: true },
        ],
      },
    ],
    defaultProps: { mode: "static", zoom: 1, fov: 50 },
    recommendedFor: [],
    requires3D: true,
    safeByDefault: false,
  },
  {
    id: "environment-3d",
    label: "Environment",
    category: "scene",
    group: "Controller",
    tier: "experimental",
    implemented: false,
    component: "EnvironmentLayer",
    description: "Drei environment map and scene lighting — does not download HDRIs",
    inspector: [
      ...defaultSections,
      {
        title: "Environment",
        controls: [
          { type: "select", key: "preset", label: "Preset", options: ["sunset", "studio", "forest", "city", "night"], defaultValue: "studio", keyframeable: false },
          { type: "slider", key: "intensity", label: "Intensity", min: 0, max: 2, step: 0.01, defaultValue: 1, keyframeable: true },
        ],
      },
    ],
    defaultProps: { preset: "studio", intensity: 1 },
    recommendedFor: [],
    requires3D: true,
    safeByDefault: false,
  },
];

export default registry;
